# Generated by Django 4.2.6 on 2024-01-19 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German'), ('Russian', 'Russian'), ('Italian', 'Italian')], max_length=30)),
                ('category', models.CharField(max_length=40)),
                ('front_native', models.CharField(max_length=50)),
                ('back_translation', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
